#!/usr/bin/env python3
"""Cross-check kjv.json / web.json / asv.json against eBible.org's official
readaloud plain-text files (generated by their own toolchain from the same
USFM). Usage: python3 crosscheck.py [kjv|web|asv]"""
import json, re, os, glob, sys

HERE = os.path.dirname(os.path.abspath(__file__))
LABEL = sys.argv[1] if len(sys.argv) > 1 else "web"
READALOUD = {"/tmp/readaloud": "web", "/tmp/ra-kjv": "kjv",
             "/tmp/ra-asv": "asv"}
RA_DIR = [d for d, l in READALOUD.items() if l == LABEL][0]
TAG = {"kjv": "eng-kjv", "web": "eng-web", "asv": "eng-asv"}[LABEL]

CODE2NAME = {"GEN":"Genesis","EXO":"Exodus","LEV":"Leviticus","NUM":"Numbers",
"DEU":"Deuteronomy","JOS":"Joshua","JDG":"Judges","RUT":"Ruth","1SA":"1 Samuel",
"2SA":"2 Samuel","1KI":"1 Kings","2KI":"2 Kings","1CH":"1 Chronicles",
"2CH":"2 Chronicles","EZR":"Ezra","NEH":"Nehemiah","EST":"Esther","JOB":"Job",
"PSA":"Psalms","PRO":"Proverbs","ECC":"Ecclesiastes","SNG":"Song of Solomon",
"ISA":"Isaiah","JER":"Jeremiah","LAM":"Lamentations","EZK":"Ezekiel",
"DAN":"Daniel","HOS":"Hosea","JOL":"Joel","AMO":"Amos","OBA":"Obadiah",
"JON":"Jonah","MIC":"Micah","NAM":"Nahum","HAB":"Habakkuk","ZEP":"Zephaniah",
"HAG":"Haggai","ZEC":"Zechariah","MAL":"Malachi","MAT":"Matthew","MRK":"Mark",
"LUK":"Luke","JHN":"John","ACT":"Acts","ROM":"Romans","1CO":"1 Corinthians",
"2CO":"2 Corinthians","GAL":"Galatians","EPH":"Ephesians","PHP":"Philippians",
"COL":"Colossians","1TH":"1 Thessalonians","2TH":"2 Thessalonians",
"1TI":"1 Timothy","2TI":"2 Timothy","TIT":"Titus","PHM":"Philemon",
"HEB":"Hebrews","JAS":"James","1PE":"1 Peter","2PE":"2 Peter","1JN":"1 John",
"2JN":"2 John","3JN":"3 John","JUD":"Jude","REV":"Revelation"}

def clean(t):
    return re.sub(r"\s+", " ", t.replace("\xa0", " ")).strip()

data = {b["n"]: b["c"] for b in json.load(
    open(os.path.join(HERE, LABEL + ".json"), encoding="utf-8"))["books"]}

total = match = 0
mismatches = []
countmismatch = []
files = 0
for code, name in CODE2NAME.items():
    for path in sorted(glob.glob(os.path.join(
            RA_DIR, f"{TAG}_*_{code}_*_read.txt"))):
        m = re.search(r'_(\d+)_read\.txt$', path)
        ch = int(m.group(1))
        files += 1
        lines = open(path, encoding="utf-8-sig").read().split("\n")
        while lines and not lines[-1].strip():
            lines.pop()
        assert lines[1].strip() == f"Chapter {ch}.", (path, lines[1])
        official = [clean(l) for l in lines[2:]]
        mine_all = data[name][ch - 1]
        # readaloud drops verses that have no text; align the rest
        mine = [v for v in mine_all if v]
        if len(mine) != len(official):
            countmismatch.append((name, ch, len(mine_all), len(mine),
                                  len(official)))
            continue
        for v, (a, b_) in enumerate(zip(mine, official), 1):
            total += 1
            if a == b_:
                match += 1
            elif len(mismatches) < 20:
                mismatches.append((name, ch, v, b_[:95], a[:95]))

print(f"[{LABEL}] files: {files}, compared {total} verses, exact match "
      f"{match} ({100.0*match/total:.2f}%)")
print("chapter count mismatches:", countmismatch[:10])
for m_ in mismatches:
    print(m_)
