/* King Solomon series data generator.
   Reads the 30 adult (KJV) case files from the original King Solomon app,
   validates them, and emits js/data-solomon.js with VG.register().
   Quote texts, options, feedback, consequences, and proverbs are never
   reworded: they are copied byte-for-byte from the source cases.
   Run: node tools/gen-solomon.js  (from verse-games/) */
const fs = require('fs');
const path = require('path');
const base = path.join(__dirname, '..');
const srcDir = path.join(base, '..', 'ts-spaces', 'king-solomon');

function jsStr(s){
  return JSON.stringify(s);
}

const html = fs.readFileSync(path.join(srcDir, 'index.html'), 'utf8');
const imgsM = html.match(/const SCENE_IMAGES=\[(.*?)\];/s);
if(!imgsM) throw new Error('SCENE_IMAGES not found in king-solomon index.html');
const imgs = imgsM[1].split(',').map(s => s.trim().replace(/^['"]|['"]$/g, ''));
const altsM = html.match(/const SCENE_ALTS=\[(.*?)\];/s);
if(!altsM) throw new Error('SCENE_ALTS not found in king-solomon index.html');
// SCENE_ALTS is a JS string array; parse entries safely
const altsSrc = altsM[1];
const alts = [];
let cur = '', q = null, escN = false;
for(const ch of altsSrc){
  if(q){
    if(escN){ cur += ch; escN = false; }
    else if(ch === '\\'){ cur += ch; escN = true; }
    else if(ch === q){ q = null; alts.push(cur); cur = ''; }
    else cur += ch;
  } else if(ch === "'" || ch === '"'){ q = ch; }
}
if(imgs.length !== 30 || alts.length !== 30)
  throw new Error('expected 30 images and 30 alts, got ' + imgs.length + '/' + alts.length);

const cases = [];
for(let n = 1; n <= 30; n++){
  const p = path.join(srcDir, 'assets', 'cases', 'adult-' + String(n).padStart(2, '0') + '.json');
  const c = JSON.parse(fs.readFileSync(p, 'utf8'));
  if(c.id !== n) throw new Error('case id mismatch at ' + n);
  if(!c.title || !c.story || !c.setting) throw new Error('case ' + n + ' missing text');
  if(!Array.isArray(c.options) || c.options.length !== 3)
    throw new Error('case ' + n + ' must have 3 options');
  const correct = c.options.filter(o => o.correct);
  if(correct.length !== 1) throw new Error('case ' + n + ' must have exactly one correct option');
  c.options.forEach((o, i) => {
    if(!o.text || !o.feedback) throw new Error('case ' + n + ' option ' + i + ' missing text');
    if(!o.anchor || !o.anchor.ref || !o.anchor.quote)
      throw new Error('case ' + n + ' option ' + i + ' missing proverb anchor');
  });
  if(n > 10 && !c.consequence)
    throw new Error('case ' + n + ' (scrolls 2-3) must have a consequence');
  const ext = path.extname(imgs[n-1]);
  const img = 'img/solomon-case-' + String(n).padStart(2, '0') + ext;
  if(!fs.existsSync(path.join(base, img))) throw new Error('image missing: ' + img);
  const all = [c.title, c.story, c.setting, c.question || '', c.consequence || '',
    ...c.options.flatMap(o => [o.text, o.feedback, o.anchor.ref, o.anchor.quote])].join(' ');
  if(/[\u2013\u2014]/.test(all)) throw new Error('case ' + n + ' contains em/en dash');
  if(/<\/script/i.test(all)) throw new Error('case ' + n + ' contains </script>');
  cases.push({
    id: n,
    title: c.title,
    setting: c.setting,
    kind: c.kind === 'SCRIPTURE' ? 'SCRIPTURE' : 'STORY',
    reference: c.reference || '',
    story: c.story,
    question: c.question || 'What is your judgment?',
    consequence: c.consequence || '',
    image: img,
    alt: alts[n-1].replace(/\\'/g, "'"),
    options: c.options.map(o => ({
      text: o.text,
      correct: o.correct ? 1 : 0,
      feedback: o.feedback,
      anchor: { ref: o.anchor.ref, quote: o.anchor.quote }
    }))
  });
}

const scrollMeta = [
  { name: 'The first scroll · Cases of the court', cases: cases.slice(0, 10) },
  { name: 'The second scroll · Training in Proverbs', cases: cases.slice(10, 20) },
  { name: 'The third scroll · Wisdom in the Gates', cases: cases.slice(20, 30) }
];

const out =
'/* King Solomon: 30-case judgment series data. Generated by tools/gen-solomon.js\n' +
'   from the original King Solomon app sources (adult/KJV cases). Texts are never\n' +
'   reworded. Do not hand-edit. */\n' +
'VG.register({\n' +
'id:"king-solomon",\n' +
'title:"King Solomon",\n' +
'kicker:"KJV \\u00b7 Proverbs in the court",\n' +
'source:"1 Kings 3 \\u00b7 the court of Solomon",\n' +
'desc:"Sit as judge in Solomon\\u2019s court. Hear each cause, choose among three judgments, and let the proverbs train your ear. Scroll One is gentle; from Scroll Two a wrong judgment bears its cost.",\n' +
'meta:"3 scrolls \\u00b7 30 cases \\u00b7 judge each cause",\n' +
'shelf:"mix",\n' +
'mode:"solomon",\n' +
'playable:true,\n' +
'art:"img/card-king-solomon.webp",\n' +
'scrolls:' + JSON.stringify(scrollMeta) + '\n' +
'});\n';

const outPath = path.join(base, 'js', 'data-solomon.js');
fs.writeFileSync(outPath, out);
console.log('wrote', outPath, '-', cases.length, 'cases,', out.length, 'bytes');
