/* Verse Games data: TRIBES
   Fifty characters matched to tribe, deed and verse.
   Verse text is filled/verified from the KJV by tools/fill-verses.js */
VG.register({
id:"tribes",
title:"Tribes",
kicker:"KJV · Genesis 49",
source:"Tribal records · Genesis 49",
desc:"Fifty characters matched to tribe, deed and verse, plus Jacob's blessing over his twelve sons.",
meta:"5 stages · 50 questions · three-strike",
shelf:"knowledge",
art:"img/card-tribes.webp",
playable:true,
seal:{ref:"Genesis 49:28",verse:"All these are the twelve tribes of Israel: and this is it that their father spake unto them, and blessed them; every one according to his blessing he blessed them."},
stages:[
{name:"Stage 1 · Jacob's Blessing", questions:[
{q:"'Unstable as water, thou shalt not excel.' To which son did Jacob say this?",options:["Reuben","Simeon","Levi","Judah"],a:0,ref:"Genesis 49:4",verse:"Unstable as water, thou shalt not excel; because thou wentest up to thy father’s bed; then defiledst thou it: he went up to my couch.",insight:"Reuben lost the firstborn's honor through sin, yet grace still numbered him among the twelve."},
{q:"'Judah is a lion's whelp.' From which tribe would the promised King come?",options:["Judah","Joseph","Benjamin","Dan"],a:0,ref:"Genesis 49:9",verse:"Judah is a lion’s whelp: from the prey, my son, thou art gone up: he stooped down, he couched as a lion, and as an old lion; who shall rouse him up?",insight:"The lion of Judah became the Bible's picture of Christ the King."},
{q:"'The sceptre shall not depart from Judah, nor a lawgiver from between his feet.' To which tribe was the sceptre promised?",options:["Judah","Ephraim","Levi","Benjamin"],a:0,ref:"Genesis 49:10",verse:"The sceptre shall not depart from Judah, nor a lawgiver from between his feet, until Shiloh come; and unto him shall the gathering of the people be.",insight:"Shiloh points to Christ, the one to whom the gathering of the people would be."},
{q:"'Zebulun shall dwell at the haven of the sea.' Which tribe is blessed here?",options:["Zebulun","Asher","Naphtali","Issachar"],a:0,ref:"Genesis 49:13",verse:"Zebulun shall dwell at the haven of the sea; and he shall be for an haven of ships; and his border shall be unto Zidon.",insight:"Zebulun's portion touched the trade routes, and later heard Christ preach in Galilee."},
{q:"'Issachar is a strong ass couching down between two burdens.' Which tribe?",options:["Issachar","Zebulun","Gad","Asher"],a:0,ref:"Genesis 49:14",verse:"Issachar is a strong ass couching down between two burdens:",insight:"Strength submitted to labor: Issachar became known for understanding the times."},
{q:"'Dan shall judge his people, as one of the tribes of Israel.' Which tribe?",options:["Dan","Gad","Naphtali","Asher"],a:0,ref:"Genesis 49:16",verse:"Dan shall judge his people, as one of the tribes of Israel.",insight:"Dan means judge; Samson, the great judge, was a Danite."},
{q:"'Dan shall be a serpent by the way, an adder in the path, that biteth the horse heels.' Which tribe?",options:["Dan","Benjamin","Gad","Naphtali"],a:0,ref:"Genesis 49:17",verse:"Dan shall be a serpent by the way, an adder in the path, that biteth the horse heels, so that his rider shall fall backward.",insight:"Small but strategic: Dan's warriors were known for cunning in battle."},
{q:"'Gad, a troop shall overcome him: but he shall overcome at the last.' Which tribe?",options:["Gad","Reuben","Simeon","Levi"],a:0,ref:"Genesis 49:19",verse:"Gad, a troop shall overcome him: but he shall overcome at the last.",insight:"Gad's name means troop; his sons became mighty men of war."},
{q:"'Out of Asher his bread shall be fat, and he shall yield royal dainties.' Which tribe?",options:["Asher","Zebulun","Issachar","Naphtali"],a:0,ref:"Genesis 49:20",verse:"Out of Asher his bread shall be fat, and he shall yield royal dainties.",insight:"Asher's coastal land was rich in olive oil, fit for a king's table."},
{q:"'Naphtali is a hind let loose: he giveth goodly words.' Which tribe?",options:["Naphtali","Dan","Asher","Gad"],a:0,ref:"Genesis 49:21",verse:"Naphtali is a hind let loose: he giveth goodly words.",insight:"Swiftness and eloquence marked Naphtali; Deborah sang of their courage."},
{q:"'Joseph is a fruitful bough, even a fruitful bough by a well.' Which son?",options:["Joseph","Benjamin","Ephraim","Manasseh"],a:0,ref:"Genesis 49:22",verse:"Joseph is a fruitful bough, even a fruitful bough by a well; whose branches run over the wall:",insight:"Joseph's fruitfulness overflowed every boundary, blessing Egypt and his brothers."},
{q:"'Benjamin shall ravin as a wolf.' Which tribe is blessed here?",options:["Benjamin","Dan","Gad","Judah"],a:0,ref:"Genesis 49:27",verse:"Benjamin shall ravin as a wolf: in the morning he shall devour the prey, and at night he shall divide the spoil.",insight:"Fierce warriors came from Benjamin: King Saul, and later the apostle Paul."},
{q:"'Simeon and Levi are brethren; instruments of cruelty are in their habitations.' Which two brothers?",options:["Simeon and Levi","Reuben and Gad","Dan and Naphtali","Issachar and Zebulun"],a:0,ref:"Genesis 49:5",verse:"Simeon and Levi are brethren; instruments of cruelty are in their habitations.",insight:"Their cruelty at Shechem cost them a united inheritance; Levi's scattering became the priesthood."}
]},
{name:"Stage 2 · Sons of Jacob", questions:[
{q:"Which son was Jacob's firstborn?",options:["Reuben","Simeon","Levi","Judah"],a:0,ref:"Genesis 29:32",verse:"And Leah conceived, and bare a son, and she called his name Reuben: for she said, Surely the LORD hath looked upon my affliction; now therefore my husband will love me.",insight:"Reuben means behold a son; the firstborn's rights passed to Joseph's sons."},
{q:"Leah named this son saying, 'Now will I praise the LORD.'",options:["Judah","Levi","Simeon","Issachar"],a:0,ref:"Genesis 29:35",verse:"And she conceived again, and bare a son: and she said, Now will I praise the LORD: therefore she called his name Judah; and left bearing.",insight:"Judah means praise; from the tribe of praise came David and Christ."},
{q:"Rachel's handmaid Bilhah bore this son, and Rachel said, 'God hath judged me.'",options:["Dan","Naphtali","Gad","Asher"],a:0,ref:"Genesis 30:6",verse:"And Rachel said, God hath judged me, and hath also heard my voice, and hath given me a son: therefore called she his name Dan.",insight:"Dan means judge, a name that shaped the tribe's calling."},
{q:"'With great wrestlings have I wrestled with my sister, and I have prevailed.'",options:["Naphtali","Dan","Asher","Gad"],a:0,ref:"Genesis 30:8",verse:"And Rachel said, With great wrestlings have I wrestled with my sister, and I have prevailed: and she called his name Naphtali.",insight:"Naphtali means my wrestling; Rachel's struggle became a tribe's name."},
{q:"Rachel said, 'God hath taken away my reproach,' and named him...",options:["Joseph","Benjamin","Ephraim","Manasseh"],a:0,ref:"Genesis 30:23",verse:"And she conceived, and bare a son; and said, God hath taken away my reproach:",insight:"Joseph means increase; Rachel's shame turned to double fruitfulness."},
{q:"'The LORD shall add to me another son.' Which son's name carries this prayer?",options:["Joseph","Benjamin","Dan","Naphtali"],a:0,ref:"Genesis 30:24",verse:"And she called his name Joseph; and said, The LORD shall add to me another son.",insight:"God answered: Benjamin was born later, completing Rachel's two sons."},
{q:"Dying, Rachel named him Benoni, son of my sorrow; Jacob renamed him...",options:["Benjamin","Joseph","Ephraim","Manasseh"],a:0,ref:"Genesis 35:18",verse:"And it came to pass, as her soul was in departing, (for she died) that she called his name Ben-oni: but his father called him Benjamin.",insight:"From son of sorrow to son of the right hand: grief turned to honor."},
{q:"Leah's handmaid Zilpah bore a son, and Leah said, 'A troop cometh.'",options:["Gad","Asher","Issachar","Zebulun"],a:0,ref:"Genesis 30:11",verse:"And Leah said, A troop cometh: and she called his name Gad.",insight:"Gad means troop; his tribe became famous for mighty warriors."},
{q:"'Happy am I, for the daughters will call me blessed.' Which son did Leah name for this happiness?",options:["Asher","Gad","Issachar","Zebulun"],a:0,ref:"Genesis 30:13",verse:"And Leah said, Happy am I, for the daughters will call me blessed: and she called his name Asher.",insight:"Asher means happy; his land overflowed with oil and plenty."},
{q:"'God hath given me my hire, because I have given my maiden to my husband.'",options:["Issachar","Zebulun","Levi","Judah"],a:0,ref:"Genesis 30:18",verse:"And Leah said, God hath given me my hire, because I have given my maiden to my husband: and she called his name Issachar.",insight:"Issachar means reward; his sons were known for wisdom and understanding."},
{q:"'God hath endued me with a good dowry; now will my husband dwell with me.' Which son's name means dwelling?",options:["Zebulun","Issachar","Levi","Simeon"],a:0,ref:"Genesis 30:20",verse:"And Leah said, God hath endued me with a good dowry; now will my husband dwell with me, because I have born him six sons: and she called his name Zebulun.",insight:"Zebulun means dwelling; Leah longed for a home in Jacob's heart."},
{q:"'Now this time will my husband be joined unto me, because I have born him three sons.'",options:["Levi","Judah","Simeon","Reuben"],a:0,ref:"Genesis 29:34",verse:"And she conceived again, and bare a son; and said, Now this time will my husband be joined unto me, because I have born him three sons: therefore was his name called Levi.",insight:"Levi means joined; his tribe would be joined to the LORD's service forever."}
]}
,
{name:"Stage 3 · Wilderness and Conquest", questions:[
{q:"Which tribe received no land, because the LORD God of Israel was their inheritance?",options:["Levi","Simeon","Reuben","Gad"],a:0,ref:"Joshua 13:33",verse:"But unto the tribe of Levi Moses gave not any inheritance: the LORD God of Israel was their inheritance, as he said unto them.",insight:"Levi's portion was God himself, scattered in cities to teach Israel."},
{q:"The faithful spy Caleb, who wholly followed the LORD, came from which tribe?",options:["Judah","Ephraim","Benjamin","Manasseh"],a:0,ref:"Numbers 13:6",verse:"Of the tribe of Judah, Caleb the son of Jephunneh.",insight:"Caleb's courage foreshadowed the greater Son of Judah."},
{q:"Moses renamed Oshea the son of Nun. From which tribe was Joshua?",options:["Ephraim","Manasseh","Benjamin","Dan"],a:0,ref:"Numbers 13:8",verse:"Of the tribe of Ephraim, Oshea the son of Nun.",insight:"From Ephraim came the captain who led Israel into rest."},
{q:"Which tribe camped on the east side under Judah's standard?",options:["Zebulun","Dan","Asher","Naphtali"],a:0,ref:"Numbers 2:7",verse:"Then the tribe of Zebulun: and Eliab the son of Helon shall be captain of the children of Zebulun.",insight:"Judah led the march, and Zebulun moved with him."},
{q:"Which tribe camped on the south side under Reuben's standard?",options:["Simeon","Levi","Judah","Ephraim"],a:0,ref:"Numbers 2:12",verse:"And those which pitch by him shall be the tribe of Simeon: and the captain of the children of Simeon shall be Shelumiel the son of Zurishaddai.",insight:"Reuben's company on the south: Reuben, Simeon, and Gad."},
{q:"In the second census, which tribe was largest at 74,600 fighting men?",options:["Judah","Dan","Simeon","Ephraim"],a:0,ref:"Numbers 26:22",verse:"These are the families of Judah according to those that were numbered of them, threescore and sixteen thousand and five hundred.",insight:"Judah led in number as he would lead in promise."},
{q:"Which tribe had shrunk to 22,000, the smallest in the second census?",options:["Simeon","Levi","Benjamin","Manasseh"],a:0,ref:"Numbers 26:14",verse:"These are the families of the Simeonites, twenty and two thousand and two hundred.",insight:"Simeon's decline fulfilled Jacob's word: I will divide them in Jacob."},
{q:"Which tribes asked Moses for their inheritance east of Jordan?",options:["Reuben, Gad, and half of Manasseh","Judah, Simeon, and Benjamin","Dan, Naphtali, and Asher","Ephraim, Issachar, and Zebulun"],a:0,ref:"Numbers 32:33",verse:"And Moses gave unto them, even to the children of Gad, and to the children of Reuben, and unto half the tribe of Manasseh the son of Joseph, the kingdom of Sihon king of the Amorites, and the kingdom of Og king of Bashan, the land, with the cities thereof in the coasts, even the cities of the country round about.",insight:"They chose the near pasture over the promised land, a warning about settling for less."},
{q:"The daughters of Zelophehad, who asked for their father's inheritance, belonged to which tribe?",options:["Manasseh","Ephraim","Benjamin","Dan"],a:0,ref:"Numbers 27:1",verse:"Then came the daughters of Zelophehad, the son of Hepher, the son of Gilead, the son of Machir, the son of Manasseh, of the families of Manasseh the son of Joseph: and these are the names of his daughters; Mahlah, Noah, and Hoglah, and Milcah, and Tirzah.",insight:"Their faith secured inheritance rights for daughters in Israel."},
{q:"When Israel broke camp, which tribe set forward first?",options:["Judah","Reuben","Ephraim","Dan"],a:0,ref:"Numbers 10:14",verse:"In the first place went the standard of the camp of the children of Judah according to their armies: and over his host was Nahshon the son of Amminadab.",insight:"Praise led the procession; Judah, whose name means praise, always marched first."},
{q:"Which tribe was set apart to bear the ark of the covenant?",options:["Levi","Judah","Ephraim","Benjamin"],a:0,ref:"Deuteronomy 10:8",verse:"At that time the LORD separated the tribe of Levi, to bear the ark of the covenant of the LORD, to stand before the LORD to minister unto him, and to bless in his name, unto this day.",insight:"Levi's scattering became a blessing: priests and teachers in every corner of the land."},
{q:"Whose rod budded with almonds, confirming God's chosen priesthood?",options:["Aaron, of the tribe of Levi","Korah, of the tribe of Levi","Nahshon, of the tribe of Judah","Elishama, of the tribe of Ephraim"],a:0,ref:"Numbers 17:8",verse:"And it came to pass, that on the morrow Moses went into the tabernacle of witness; and, behold, the rod of Aaron for the house of Levi was budded, and brought forth buds, and bloomed blossoms, and yielded almonds.",insight:"God confirmed Levi's calling with life from dead wood."}
]},
{name:"Stage 4 · Judges and Kings", questions:[
{q:"In Deborah's song, from which tribe came a root of fighters against Amalek?",options:["Ephraim","Manasseh","Benjamin","Dan"],a:0,ref:"Judges 5:14",verse:"Out of Ephraim was there a root of them against Amalek; after thee, Benjamin, among thy people; out of Machir came down governors, and out of Zebulun they that handle the pen of the writer.",insight:"Deborah remembered every tribe's part, whether they came or stayed home."},
{q:"'Why did Dan remain in ships?' Deborah asked it of which tribe?",options:["Dan","Asher","Naphtali","Zebulun"],a:0,ref:"Judges 5:17",verse:"Gilead abode beyond Jordan: and why did Dan remain in ships? Asher continued on the sea shore, and abode in his breaches.",insight:"Comfort by the shore kept Dan from the battle; ease can be its own defeat."},
{q:"'For the divisions of Reuben there were great searchings of heart.' Which tribe hesitated?",options:["Reuben","Gad","Manasseh","Simeon"],a:0,ref:"Judges 5:16",verse:"Why abodest thou among the sheepfolds, to hear the bleatings of the flocks? For the divisions of Reuben there were great searchings of heart.",insight:"Reuben debated until the battle passed; indecision is a decision."},
{q:"Gideon, the least in his father's house, came from which tribe?",options:["Manasseh","Ephraim","Benjamin","Naphtali"],a:0,ref:"Judges 6:15",verse:"And he said unto him, Oh my Lord, wherewith shall I save Israel? behold, my family is poor in Manasseh, and I am the least in my father’s house.",insight:"God delights to choose the least; Manasseh's smallest became Israel's deliverer."},
{q:"After the war over Gibeah, which tribe fled to the rock Rimmon, only 600 men left?",options:["Benjamin","Simeon","Levi","Dan"],a:0,ref:"Judges 20:47",verse:"But six hundred men turned and fled to the wilderness unto the rock Rimmon, and abode in the rock Rimmon four months.",insight:"Benjamin's sin nearly erased Benjamin; grace preserved a remnant."},
{q:"Israel's first king, Saul the son of Kish, came from which tribe?",options:["Benjamin","Judah","Ephraim","Manasseh"],a:0,ref:"1 Samuel 9:2",verse:"And he had a son, whose name was Saul, a choice young man, and a goodly: and there was not among the children of Israel a goodlier person than he: from his shoulders and upward he was higher than any of the people.",insight:"Benjamin's ravening wolf became Israel's first king, tall and tragic."},
{q:"David the son of Jesse the Bethlehemite belonged to which tribe?",options:["Judah","Benjamin","Ephraim","Levi"],a:0,ref:"1 Samuel 17:12",verse:"Now David was the son of that Ephrathite of Bethlehemjudah, whose name was Jesse; and he had eight sons: and the man went among men for an old man in the days of Saul.",insight:"The shepherd of Bethlehem carried Judah's sceptre promise."},
{q:"Jeroboam, who led ten tribes away from Rehoboam, was of which tribe?",options:["Ephraim","Manasseh","Dan","Naphtali"],a:0,ref:"1 Kings 11:26",verse:"And Jeroboam the son of Nebat, an Ephrathite of Zereda, Solomon’s servant, whose mother’s name was Zeruah, a widow woman, even he lifted up his hand against the king.",insight:"Ephraim's pride split the kingdom; the northern tribes never returned."}
]},
{name:"Stage 5 · Prophets, Exile, and Promise", questions:[
{q:"In Revelation's sealing of the 144,000, which tribe is named first?",options:["Judah","Reuben","Gad","Levi"],a:0,ref:"Revelation 7:5",verse:"Of the tribe of Juda were sealed twelve thousand. Of the tribe of Reuben were sealed twelve thousand. Of the tribe of Gad were sealed twelve thousand.",insight:"Judah still leads the list; the Lion's tribe is named first to the end."},
{q:"'The Lion of the tribe of Juda, the Root of David, hath prevailed.' Which tribe?",options:["Judah","Benjamin","Levi","Ephraim"],a:0,ref:"Revelation 5:5",verse:"And one of the elders saith unto me, Weep not: behold, the Lion of the tribe of Juda, the Root of David, hath prevailed to open the book, and to loose the seven seals thereof.",insight:"Every blessing on Judah was heading here: to Christ."},
{q:"Of Benjamin Moses said, 'The beloved of the LORD shall dwell in safety by him.' Which tribe?",options:["Benjamin","Judah","Levi","Simeon"],a:0,ref:"Deuteronomy 33:12",verse:"And of Benjamin he said, The beloved of the LORD shall dwell in safety by him; and the LORD shall cover him all the day long, and he shall dwell between his shoulders.",insight:"The smallest tribe became the beloved, sheltered between God's shoulders."},
{q:"'Let Reuben live, and not die, and let not his men be few.' For which tribe did Moses pray this?",options:["Reuben","Simeon","Levi","Gad"],a:0,ref:"Deuteronomy 33:6",verse:"Let Reuben live, and not die; and let not his men be few.",insight:"Moses prayed life over the tribe that had forfeited its birthright; grace again."},
{q:"'Blessed of the LORD be his land, for the precious things of heaven, for the dew.' Of whom did Moses say this?",options:["Joseph","Reuben","Gad","Dan"],a:0,ref:"Deuteronomy 33:13",verse:"And of Joseph he said, Blessed of the LORD be his land, for the precious things of heaven, for the dew, and for the deep that coucheth beneath,",insight:"Joseph's double portion: heaven's dew above and the deep below."}
]}
]
});
